# Generated by Django 3.2.10 on 2021-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0002_auto_20211217_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='price',
            field=models.IntegerField(),
        ),
    ]
