# Generated by Django 3.2.7 on 2022-02-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_alter_dev_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('mobile_name', models.CharField(max_length=50)),
                ('problem', models.TextField(max_length=200)),
                ('pic', models.ImageField(upload_to='img')),
            ],
        ),
    ]
