# Generated by Django 3.2.7 on 2022-02-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pic',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
